language: python

jobs:
  include:
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: osx
      language: generic
      python: 3.6
    - os: osx
      language: generic
      python: 3.7

branches:
  only:
  - master

# command to install dependencies
install:
  - pip3 install ".[dev]"
# command to run tests
script:
  - pytest
  - python3 -c 'from hello_ci import HelloCI; HelloCI().greet()'
