format_version: 3
pipelines:
  Hello-CI:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git:
        git: https://github.com/UCL-RITS/hello_ci
        shallow_clone: false
        auto_update: true
        branch: master
    stages:
    - test:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          test:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - -c
                - pwd
                command: bash
                run_if: passed
            - exec:
                arguments:
                - install
                - --user
                - .[dev]
                command: pip3
                run_if: passed
            - exec:
                arguments:
                - -m
                - pytest
                command: python3
                run_if: passed
            - exec:
                arguments:
                - -c
                - from hello_ci import HelloCI; HelloCI().greet()
                command: python3
                run_if: passed
