on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '3.6', '3.7' ]
    name: Python ${{ matrix.python-version }} sample on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Test with pytest
        run: |
          pip install pytest
          pytest
          python -c "from hello_ci import HelloCI; HelloCI().greet()"
