on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, test]
    name: Python on test's computer
    steps:
      - uses: actions/checkout@v3
      - name: Test runners
        run: |
          echo 'Hello, world!'
          sleep 120
