on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, test]
    name: Python on test's computer
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          python3 -m venv env
          source env/bin/activate
          python3 -m pip install --upgrade pip
          pip3 install .[dev]
      - name: Test with pytest
        run: |
          source env/bin/activate
          pip3 install pytest
          pytest
          python3 -c "from hello_ci import HelloCI; HelloCI().greet()"
