on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    name: Python on mose's computer
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          python -m venv env
          source env/bin/activate
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Test with pytest
        run: |
          source env/bin/activate
          pip install pytest
          pytest
          python -c "from hello_ci import HelloCI; HelloCI().greet()"
