on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:

jobs:
  build:
    runs-on: [self-hosted, test]
    name: Python on test's computer
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          echo "hello world"
      - name: Test with pytest
        run: |
          echo 'Ciao mondo!'
